version: "3.8"
services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    expose:
      - "5432"
    volumes:
      - "postgres_db_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

volumes:
  postgres_db_data:
    external: true
