"""
Esmerald settings for {{ cookiecutter.project_name }} project.

Generated by 'esmerald-admin createproject' using Esmerald 0.2.5.
"""

import logging
import sys
from typing import Any, List, Optional

from esmerald.conf.enums import EnvironmentType
from esmerald.logging import InterceptHandler
from loguru import logger

from ..settings import AppSettings, CORSConfig


class DevelopmentAppSettings(AppSettings):
    debug: bool = True
    app_name: str = "My application in development mode."
    title: str = "{{ cookiecutter.project_name }} - Development"
    environment: Optional[str] = EnvironmentType.DEVELOPMENT
    version: str = "2.0.0"
    enable_openapi: bool = True
    allowed_hosts: Optional[List[str]] = ["*"]
    cors_origins: Optional[List[str]] = [
        "http://localhost",
        "http://localhost:3000",
        "http://localhost:4000",
    ]

    def __init__(self, *args: Any, **kwds: Any) -> Any:
        super().__init__(*args, **kwds)
        logging_level = logging.DEBUG if self.debug else logging.INFO
        loggers = ("uvicorn.asgi", "uvicorn.access", "esmerald")
        logging.getLogger().handlers = [InterceptHandler()]
        for logger_name in loggers:
            logging_logger = logging.getLogger(logger_name)
            logging_logger.handlers = [InterceptHandler(level=logging_level)]

        logger.configure(handlers=[{"sink": sys.stderr, "level": logging_level}])

    @property
    def cors_config(self) -> CORSConfig:
        return CORSConfig(allow_origins=self.cors_origins)
